# Generated by Django 5.1.6 on 2025-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('sports', 'Sports'), ('random', 'Random'), ('literature', 'Literature'), ('video_games', 'Video Games'), ('movies', 'Movies'), ('music', 'Music'), ('anime', 'Anime'), ('mythology', 'Mythology'), ('nature', 'Nature'), ('comics', 'Comics'), ('cartoons', 'Cartoons')], max_length=50),
        ),
    ]
