# Generated by Django 5.1.6 on 2025-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='selected_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
