# Generated by Django 5.1.6 on 2025-03-04 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_gameroom_finished_at_gameroom_selected_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='PlayerGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz_app.gamestate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
