# Generated by Django 5.1.6 on 2025-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
