services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 quiz_project.asgi:application"
    volumes:
      - .:/app
      - ./static:/app/staticfiles  # Sync static files
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensure DB is ready before running Django
      redis:
        condition: service_started
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6380:6380"  # Redis default port is 6379, not 6380
    command: ["redis-server", "--port", "6380"]

volumes:
  postgres_data:
